### PR TITLE
RHMAP-10129 Update to Swift 3

### PR DESCRIPTION
**Pull request by aidenkeating**

### CODE REVIEW

**Comment by aidenkeating** [comment]
@jcesarmobile Would you mind taking a look please?

**Comment by aidenkeating** [comment]
@corinnekrych Could you take a look please?

**Comment by corinnekrych** [comment]
👀

**Comment by corinnekrych** [comment]
@aidenkeating As discussed I think we need to patch fh-ios-swift-sdk in [here](https://github.com/feedhenry/fh-ios-swift-sdk/blob/master/FeedHenry/Cloud/AuthRequest.swift#L36) it should be:
var param: [String: Any] = [:]
Tested with this patch, I got this: https://www.dropbox.com/s/ea5zjrp4ad5yvos/Screenshot%202016-11-21%2018.16.08.png?dl=0
as per Google recommendation the webview is deprecated but still working untill 20thApril 2017

**Comment by aidenkeating** [comment]
@corinnekrych I've updated the dependency to `5.0.1` so now everything should be working fine

**Comment by corinnekrych** [comment]
+1

**Pull request merged**
