### PR TITLE
RHMAP-10102 Update to Swift 2.3

### PR DESCRIPTION
**Pull request by aidenkeating**
This updates the project to Swift 2.3.

### CODE REVIEW

**Comment by aidenkeating** [comment]
@jcesarmobile @corinnekrych Would you mind taking a look? I was using a few of these tasks just to get some small understanding of Swift.

**Comment by corinnekrych** [comment]
@aidenkeating as discussed, let's have a swift2.3 branch instead of merging it to master

**Comment by aidenkeating** [comment]
@corinnekrych Done

**Comment by jcesarmobile** [comment]
LGTM

**Pull request merged**
